# Generated by Codex on 2026-06-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_isbn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sale_date", models.DateField()),
                ("channel", models.CharField(blank=True, max_length=100)),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales", to="books.book")),
            ],
            options={
                "ordering": ["-sale_date"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="authors_m2m",
            field=models.ManyToManyField(blank=True, related_name="books", to="books.author"),
        ),
    ]
