# Generated by Codex on 2026-06-14

import re

from django.db import migrations


AUTHOR_SPLIT_RE = re.compile(r"\s*(?:,|;|&|/| and )\s*", re.IGNORECASE)


def split_authors(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    Author = apps.get_model("books", "Author")

    for book in Book.objects.all():
        names = [name for name in AUTHOR_SPLIT_RE.split(book.authors) if name.strip()]

        for name in names:
            author, _ = Author.objects.get_or_create(name=name.strip())
            book.authors_m2m.add(author)


def merge_authors(apps, schema_editor):
    Book = apps.get_model("books", "Book")

    for book in Book.objects.all():
        names = list(book.authors_m2m.values_list("name", flat=True))
        book.authors = ", ".join(names)
        book.save(update_fields=["authors"])


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_author_sale"),
    ]

    operations = [
        migrations.RunPython(split_authors, merge_authors),
    ]
