# Generated by Codex on 2026-06-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_split_authors_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="authors_m2m",
            new_name="authors",
        ),
    ]
