# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_replace_authors_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="stock_on_hand",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="reorder_threshold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
