# Generated by Django 5.2.15 on 2026-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_multitenancy_and_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
