# Generated by Django 5.2.15 on 2026-06-14 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_accesscode_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingActivation',
            fields=[
            ],
            options={
                'verbose_name': 'Pending activation',
                'verbose_name_plural': 'Pending activations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.profile',),
        ),
    ]
