# Generated by Django 5.2.15 on 2026-06-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_pendingactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='distribution_expense',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distribution expense'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(verbose_name='Published date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=200, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=0, verbose_name='Reorder threshold'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock_on_hand',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock on hand'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='books.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='channel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(verbose_name='Sale date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Unit price'),
        ),
    ]
