# Generated by Django 5.2.15 on 2026-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_return_supplier_reorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
