# Generated by Django 5.2.15 on 2026-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_low_stock_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Unit cost'),
        ),
    ]
