# Generated by Django 5.2.15 on 2026-06-15 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_reorder_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='Change')),
                ('resulting_stock', models.PositiveIntegerField(verbose_name='Resulting stock')),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('found', 'Found'), ('correction', 'Correction'), ('other', 'Other')], default='correction', max_length=20, verbose_name='Reason')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='books.book', verbose_name='Book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stock_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
