# Generated by Django 5.2.15 on 2026-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed at'),
        ),
        migrations.AddField(
            model_name='printrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('found', 'Found'), ('correction', 'Correction'), ('production', 'Print run'), ('other', 'Other')], default='correction', max_length=20, verbose_name='Reason'),
        ),
    ]
