# Generated by Django 5.2.15 on 2026-06-19 11:19

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_printrun_completed_at_printrun_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[books.models.validate_avatar_size], verbose_name='Avatar'),
        ),
    ]
