# Generated by Django 5.2.15 on 2026-06-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('SAR', 'SAR'), ('AED', 'AED'), ('MAD', 'MAD'), ('DZD', 'DZD'), ('TND', 'TND'), ('EGP', 'EGP'), ('TRY', 'TRY')], default='USD', max_length=3, verbose_name='Currency')),
                ('payment_date', models.DateField(verbose_name='Payment date')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_payments', to='books.author', verbose_name='Author')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_royalty_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
