# Generated by Django 5.2.15 on 2026-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_customerlogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='integration',
            name='platform',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('amazon', 'Amazon'), ('stripe', 'Stripe')], max_length=20, verbose_name='Platform'),
        ),
    ]
