# Generated by Django 5.2.15 on 2026-06-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='checkout_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_customer_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('UNPAID', 'Unpaid'), ('UPGRADED', 'Upgraded'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='INCOMPLETE', max_length=20),
        ),
    ]
