# Generated by Django 5.2.15 on 2026-06-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_account_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='books.account'),
        ),
    ]
