# Generated by Django 5.2.15 on 2026-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_backfill_subscription_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, verbose_name='Cover image URL'),
        ),
    ]
