# Generated by Django 5.2.15 on 2026-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_book_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='api_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='API secret'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='Webhook secret'),
        ),
    ]
