# Generated by Django 5.2.15 on 2026-06-21 16:21

import books.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_encrypt_integration_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=books.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='api_secret',
            field=books.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='API secret'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='webhook_secret',
            field=books.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Webhook secret'),
        ),
    ]
