# Generated by Django 5.2.15 on 2026-06-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_alter_integration_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_orders', to='books.integration')),
            ],
            options={
                'unique_together': {('integration', 'order_id')},
            },
        ),
    ]
