# Generated by Django 5.2.15 on 2026-06-21 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0041_processedshopifyorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default retail price, used to pre-fill checkout and sale forms.', max_digits=8, null=True, verbose_name='List price'),
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=20, verbose_name='Receipt number')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10, verbose_name='Payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.account')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_transactions', to='books.customer', verbose_name='Customer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_transactions', to='books.location', verbose_name='Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sale_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='books.saletransaction', verbose_name='Transaction'),
        ),
    ]
