# Generated by Django 5.2.15 on 2026-06-21 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_book_list_price_saletransaction_sale_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='saletransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_number', ''), _negated=True), fields=('account', 'receipt_number'), name='unique_receipt_number_per_account'),
        ),
    ]
