# Generated by Django 5.2.15 on 2026-06-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0043_saletransaction_unique_receipt_number_per_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pre-fills the tax rate on each new checkout cart line.', max_digits=5, verbose_name='Default tax rate (%)'),
        ),
    ]
