# Generated by Django 5.2.15 on 2026-06-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0044_account_default_tax_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesalerFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Wholesale price')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock quantity')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_wholesaler_feed_items', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='books.supplier', verbose_name='Supplier')),
            ],
            options={
                'ordering': ['isbn'],
                'unique_together': {('supplier', 'isbn')},
            },
        ),
    ]
