# Generated by Django 5.2.15 on 2026-06-22 14:23

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0045_wholesalerfeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='brand_color',
            field=models.CharField(blank=True, help_text='Used for titles and accents on your invoices and receipts, e.g. #1f1f1f.', max_length=7, validators=[books.models.validate_hex_color], verbose_name='Brand color'),
        ),
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown on your invoices and receipts. Leave empty to show no logo.', null=True, upload_to='account_logos/', validators=[books.models.validate_logo_size], verbose_name='Logo'),
        ),
    ]
