# Generated by Django 5.2.15 on 2026-06-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0046_account_brand_color_account_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='platform',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('amazon', 'Amazon'), ('stripe', 'Stripe'), ('cinetpay', 'CinetPay')], max_length=20, verbose_name='Platform'),
        ),
    ]
