"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-k^rrsrc4tq2hl&ny!l*5@x!z((#a_rl=7hae#e&p=6a_=xh5xl",
)

# Encrypts Integration.api_key/api_secret/webhook_secret at rest (see
# books/fields.py). Dev-only fallback below, like SECRET_KEY above - must be
# overridden via .env in production. Generate a real key with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
FIELD_ENCRYPTION_KEY = os.environ.get(
    "FIELD_ENCRYPTION_KEY",
    "AN6JArALF8TZfOxSJNOZk5wVQd95nTXwAYI7XWX_Df4=",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [host.strip() for host in os.environ.get("ALLOWED_HOSTS", "").split(",") if host.strip()]

CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'books',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'books.middleware.AccountContextMiddleware',
    'books.middleware.SubscriptionRequiredMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# django-axes: lock out an IP+username combo after repeated failed logins
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "registration/lockout.html"

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get("DB_ENGINE") == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "rumipress"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('ar', 'العربية'),
    ('tr', 'Türkçe'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Production hardening (no-ops in local dev, where DEBUG defaults to True)
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# AI chat assistant
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")

# Email (used to send signup verification codes)
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

VERIFICATION_CODE_TTL_MINUTES = 15

CUSTOMER_PORTAL_TOKEN_TTL_MINUTES = 30

CUSTOMER_PORTAL_LOGIN_COOLDOWN_SECONDS = 60

# Portal sessions get their own (shorter) expiry via request.session.set_expiry()
# rather than inheriting Django's default SESSION_COOKIE_AGE (2 weeks) - the
# magic link itself expires in 30 minutes, so a stolen session cookie
# shouldn't meaningfully outlive that by weeks.
CUSTOMER_PORTAL_SESSION_AGE_SECONDS = int(os.environ.get("CUSTOMER_PORTAL_SESSION_AGE_SECONDS", "7200"))

ISBN_LOOKUP_COOLDOWN_SECONDS = 2

CHAT_API_COOLDOWN_SECONDS = 2

CSV_IMPORT_MAX_SIZE_BYTES = int(os.environ.get("CSV_IMPORT_MAX_SIZE_BYTES", str(5 * 1024 * 1024)))

VERIFICATION_CODE_MAX_ATTEMPTS = 10

ACCESS_CODE_MAX_ATTEMPTS = 10

# Platform-level billing (RumiPress charging its own account owners via
# iyzico) - distinct from the per-owner Stripe Integration model used for
# invoice payments. The trial length itself is configured on the Pricing
# Plan in the iyzico merchant panel, not passed per-request.
IYZICO_API_KEY = os.environ.get("IYZICO_API_KEY", "")
IYZICO_SECRET_KEY = os.environ.get("IYZICO_SECRET_KEY", "")
IYZICO_MERCHANT_ID = os.environ.get("IYZICO_MERCHANT_ID", "")
IYZICO_BASE_URL = os.environ.get("IYZICO_BASE_URL", "https://sandbox-api.iyzipay.com")
IYZICO_PRICING_PLAN_REFERENCE_CODE = os.environ.get("IYZICO_PRICING_PLAN_REFERENCE_CODE", "")
SUBSCRIPTION_TRIAL_DAYS = 7

# Which provider billing_start uses for platform subscription billing -
# "iyzico" (Turkey-only, card-based, has a native recurring Subscription
# product) or "cinetpay" (West Africa incl. Mali, mobile money + cards, no
# native recurring billing - each period is its own one-time checkout, same
# shape as an invoice payment). Switch by setting this env var once real
# CinetPay credentials exist; defaults to iyzico so existing setups keep
# working unchanged.
PLATFORM_BILLING_PROVIDER = os.environ.get("PLATFORM_BILLING_PROVIDER", "iyzico")

# CinetPay (West Africa mobile money/card aggregator - Orange Money, Moov
# Money, etc.) - used both for the per-owner Integration model (customer
# invoice payments) and, if PLATFORM_BILLING_PROVIDER is "cinetpay", for
# RumiPress's own platform subscription billing. CinetPay only collects in
# your account's authorized local currency (XOF for a Mali-registered
# account) - it cannot run multi-currency like Stripe/iyzico.
CINETPAY_API_KEY = os.environ.get("CINETPAY_API_KEY", "")
CINETPAY_SITE_ID = os.environ.get("CINETPAY_SITE_ID", "")
CINETPAY_BASE_URL = os.environ.get("CINETPAY_BASE_URL", "https://api-checkout.cinetpay.com/v2")
CINETPAY_CURRENCY = os.environ.get("CINETPAY_CURRENCY", "XOF")
# Amount must be a multiple of 5 per CinetPay's API constraint.
CINETPAY_SUBSCRIPTION_AMOUNT = int(os.environ.get("CINETPAY_SUBSCRIPTION_AMOUNT", "5000"))
CINETPAY_SUBSCRIPTION_PERIOD_DAYS = int(os.environ.get("CINETPAY_SUBSCRIPTION_PERIOD_DAYS", "30"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
